database:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/bukkit
  password: bukkit
  username: bukkit
  initialSize: 10
  logAbandoned: true
  maxActive: 10
  minIdle: 10
  maxIdle: -1
  maxOpenPreparedStatements: 10
  maxWait: 5000
  name: jdbc/dataSource
  poolPreparedStatements: true
  removeAbandoned: true
  removeAbandonedTimeout: 60
  testOnBorrow: true
  timeBetweenEvictionRunsMillis: 60000
  testWhileIdle: true
debug:true